### ISSUE TITLE
作者你好！我本地新建安装完之后，运行报错

### ISSUE THREAD

**Issue by lengyehan** [rootsli/vueadmin#1]
老是提示一些未定义，登录也进不去
.accordion is not a function
![image](https://cloud.githubusercontent.com/assets/8751342/19467244/b80f7dc8-9542-11e6-9fd2-ec4edc5a6f8c.png)

没有更改任何代码，这是怎么回事呢？

**Comment by rootsli** [comment]
看着像是semantic-ui没有安装成功，请配置npm源为国内淘宝镜像，再安装试下

**Comment by lengyehan** [comment]
用的就是国内镜像哦

**Comment by rootsli** [comment]
运行npm install 后 请下载项目里提到的semantic-ui-custom.rar，解压后覆盖掉node_modules\semantic-ui-css目录下内容即可（需先运行npm install）。因为使用的UI比较特殊，需要定制下。

**Comment by rootsli** [comment]
如果是新项目，建议使用vue2全家桶哈，效率比vue更高。我也做了个脚手架，后面主要会维护这个项目：https://github.com/rootsli/vue2admin
